language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codacy-coverage
script:
  python setup.py test
  coverage xml
  export CODACY_PROJECT_TOKEN=e57064de72e446728435d088294afa84
  python-codacy-coverage -r coverage.xml
after_success:
  coveralls