language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python setup.py test